# Generated by Django 5.1 on 2025-02-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='line_of_business',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='line_of_business',
            field=models.ManyToManyField(blank=True, related_name='enterprises', to='operations.lineofbusiness'),
        ),
    ]
